"DROP TABLE IF EXISTS comptes;""DROP TABLE IF EXISTS livres;"
"CREATE TABLE comptes(IdUser PRIMARY KEY AUTOINCREMENT, Nom TEXT, Prenom TEXT,Mail TEXT,Mdp TEXT,Droit TEXT);"
"CREATE TABLE livres(Isbn TEXT PRIMARY KEY , Titre TEXT,Auteur TEXT,Genre TEXT,FOREIGN KEY(IdUser) REFERENCES comptes(IdUser)), Date_Emprunt TEXT;"
"INSERT INTO comptes(Nom,Prenom,Mail,Mdp,Droit) VALUES ('Uriel','Anthony','ua@gmail.com','Password237','SAdmin');"
"INSERT INTO livres (Titre, Auteur, Genre, Dispo) VALUES ('Le Seigneur des Anneaux', 'J.R.R. Tolkien', 'Fantasy', 0);"
"INSERT INTO livres (Titre, Auteur, Genre, Dispo) VALUES ('1984', 'George Orwell', 'Dystopie', 0);"
"INSERT INTO livres (Titre, Auteur, Genre, Dispo) VALUES ('Orgueil et Préjugés', 'Jane Austen', 'Roman', 0);"
"INSERT INTO livres (Titre, Auteur, Genre, Dispo) VALUES ('L''Étranger', 'Albert Camus', 'Roman', 0);"
"INSERT INTO livres (Titre, Auteur, Genre, Dispo) VALUES ('Harry Potter à l''école des sorciers', 'J.K. Rowling', 'Fantasy', 0);"
"INSERT INTO livres (Titre, Auteur, Genre, Dispo) VALUES ('Les Misérables', 'Victor Hugo', 'Roman', 0);"
"INSERT INTO livres (Titre, Auteur, Genre, Dispo) VALUES ('Le Petit Prince', 'Antoine de Saint-Exupéry', 'Conte', 0);"
"INSERT INTO livres (Titre, Auteur, Genre, Dispo) VALUES ('To Kill a Mockingbird', 'Harper Lee', 'Roman', 0);"
"INSERT INTO livres (Titre, Auteur, Genre, Dispo) VALUES ('Crime and Punishment', 'Fyodor Dostoevsky', 'Roman', 0);"
"INSERT INTO livres (Titre, Auteur, Genre, Dispo) VALUES ('Pride and Prejudice', 'Jane Austen', 'Roman', 0);"
"INSERT INTO livres (Titre, Auteur, Genre, Dispo) VALUES ('The Great Gatsby', 'F. Scott Fitzgerald', 'Roman', 0);"
"INSERT INTO livres (Titre, Auteur, Genre, Dispo) VALUES ('One Hundred Years of Solitude', 'Gabriel García Márquez', 'Roman', 0);"
"INSERT INTO livres (Titre, Auteur, Genre, Dispo) VALUES ('Anna Karenina', 'Leo Tolstoy', 'Roman', 0);"
"INSERT INTO livres (Titre, Auteur, Genre, Dispo) VALUES ('Brave New World', 'Aldous Huxley', 'Dystopian', 0);"
"INSERT INTO livres (Titre, Auteur, Genre, Dispo) VALUES ('The Catcher in the Rye', 'J.D. Salinger', 'Roman', 0);"
"INSERT INTO livres (Titre, Auteur, Genre, Dispo) VALUES ('The Hobbit', 'J.R.R. Tolkien', 'Fantasy', 0);"
"INSERT INTO livres (Titre, Auteur, Genre, Dispo) VALUES ('The Chronicles of Narnia', 'C.S. Lewis', 'Fantasy', 0);"
"INSERT INTO livres (Titre, Auteur, Genre, Dispo) VALUES ('Moby-Dick', 'Herman Melville', 'Aventure', 0);"
"INSERT INTO livres (Titre, Auteur, Genre, Dispo) VALUES ('Wuthering Heights', 'Emily Brontë', 'Roman', 0);"
"INSERT INTO livres (Titre, Auteur, Genre, Dispo) VALUES ('Frankenstein', 'Mary Shelley', 'Gothique', 0);"
