--DROP TABLE IF EXISTS Comptes;
--CREATE TABLE Comptes(Id_User INTEGER PRIMARY KEY AUTOINCREMENT, Nom TEXT, Prenom TEXT, Mail TEXT, Hash TEXT, Admin INTEGER);
--INSERT INTO Comptes(Nom, Prenom, Mail, Hash, Admin) VALUES ('Uriel','Anthony','ua@gmail.com', '', 1);
--INSERT INTO Comptes(Nom, Prenom, Mail, Hash, Admin) VALUES ('Renard-Raguenaud','Lucien','lr@gmail.com', '', 0);
--DROP TABLE IF EXISTS Livres;
--CREATE TABLE Livres(ISBN TEXT PRIMARY KEY, Titre TEXT, Auteur TEXT, Genre TEXT, Id_User INTEGER, Date_Emprunt TEXT);
INSERT INTO Livres (ISBN, Titre, Auteur, Genre, Id_User) Values('1xxx', 'Le Seigneur des Anneaux', 'J.R.R. Tolkien', 'Fantasy', 0);
INSERT INTO Livres (ISBN, Titre, Auteur, Genre, Id_User) Values('2xxx', '1984', 'George Orwell', 'Dystopie', 0);
INSERT INTO Livres (ISBN, Titre, Auteur, Genre, Id_User) Values('3xxx', 'Orgueil et Prejuges', 'Jane Austen', 'Roman', 0);
INSERT INTO Livres (ISBN, Titre, Auteur, Genre, Id_User) Values('4xxx', 'L''etranger', 'Albert Camus', 'Roman', 0);
INSERT INTO Livres (ISBN, Titre, Auteur, Genre, Id_User) Values('5xxx', 'Harry Potter à l''ecole des sorciers', 'J.K. Rowling', 'Fantasy', 0);
INSERT INTO Livres (ISBN, Titre, Auteur, Genre, Id_User) Values('6xxx', 'Les Miserables', 'Victor Hugo', 'Roman', 0);
INSERT INTO Livres (ISBN, Titre, Auteur, Genre, Id_User) Values('7xxx', 'Le Petit Prince', 'Antoine de Saint-Exupery', 'Conte', 0);
INSERT INTO Livres (ISBN, Titre, Auteur, Genre, Id_User) Values('8xxx', 'To Kill a Mockingbird', 'Harper Lee', 'Roman', 0);
INSERT INTO Livres (ISBN, Titre, Auteur, Genre, Id_User) Values('9xxx', 'Crime and Punishment', 'Fyodor Dostoevsky', 'Roman', 0);
INSERT INTO Livres (ISBN, Titre, Auteur, Genre, Id_User) Values('10xx', 'Pride and Prejudice', 'Jane Austen', 'Roman', 0);
INSERT INTO Livres (ISBN, Titre, Auteur, Genre, Id_User) Values('11xx', 'The Great Gatsby', 'F. Scott Fitzgerald', 'Roman', 0);
INSERT INTO Livres (ISBN, Titre, Auteur, Genre, Id_User) Values('12xx', 'One Hundred Years of Solitude', 'Gabriel García Márquez', 'Roman', 0);
INSERT INTO Livres (ISBN, Titre, Auteur, Genre, Id_User) Values('13xx', 'Anna Karenina', 'Leo Tolstoy', 'Roman', 0);
INSERT INTO Livres (ISBN, Titre, Auteur, Genre, Id_User) Values('14xx', 'Brave New World', 'Aldous Huxley', 'Dystopian', 0);
INSERT INTO Livres (ISBN, Titre, Auteur, Genre, Id_User) Values('15xx', 'The Catcher in the Rye', 'J.D. Salinger', 'Roman', 0);
INSERT INTO Livres (ISBN, Titre, Auteur, Genre, Id_User) Values('16xx', 'The Hobbit', 'J.R.R. Tolkien', 'Fantasy', 0);
INSERT INTO Livres (ISBN, Titre, Auteur, Genre, Id_User) Values('17xx', 'The Chronicles of Narnia', 'C.S. Lewis', 'Fantasy', 0);
INSERT INTO Livres (ISBN, Titre, Auteur, Genre, Id_User) Values('18xx', 'Moby-Dick', 'Herman Melville', 'Aventure', 0);
INSERT INTO Livres (ISBN, Titre, Auteur, Genre, Id_User) Values('19xx', 'Wuthering Heights', 'Emily Brontë', 'Roman', 0);
INSERT INTO Livres (ISBN, Titre, Auteur, Genre, Id_User) Values('20xx', 'Frankenstein', 'Mary Shelley', 'Gothique', 0);
